import type { Metadata } from "next";
import "./globals.css";
import BackgroundComponent from "../components/Background";

export const metadata: Metadata = {
  title: "Typing speed test",
  description: "Generated by create next app",
  authors: [{ name: "github.com/mstrj" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl">
      <body className="text-foreground bg-background">
        {children}
        <BackgroundComponent />
      </body>
    </html>
  );
}
